name: ci

on:
  push:
    branches:
      - 'main'
      
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: shocnt/ads-service:${{ github.sha }}

  github:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: dd-shocnt/ecommerce-workshop-advertisement-manifests
          path: ecommerce-workshop-advertisement-manifests/overlays/dev
      - name: Create a new branch
        run: |
          cd /home/runner/work/ecommerce-workshop-advertisement/ecommerce-workshop-advertisement/ecommerce-workshop-advertisement-manifests
          git switch -c ${{ github.sha }}
  
      - name: Update rollout-patch.yaml
        run: | 
          cd /home/runner/work/ecommerce-workshop-advertisement/ecommerce-workshop-advertisement/ecommerce-workshop-advertisement-manifests/overlays/dev
          sed -i -e 's/tags.datadoghq.com\/version: .*/tags.datadoghq.com\/version: "${{ github.sha }}"/' rollout-patch.yaml
          sed -i -e 's/- image: "shocnt\/ads-service:.*"/- image: "shocnt\/ads-service:${{ github.sha }}"/' rollout-patch.yaml
          cat rollout-patch.yaml
