name: On push to master

on:
  push:
    branches:
      - master

jobs:
  show-properties:
    runs-on: ubuntu-latest
    steps:
      - name: Show github properties
        run: | 
          echo ${{ github.workflow }}
          echo ${{ github.ref }}
          echo ${{ github.sha }}
      - name: Show secret properties
        run: | 
          echo ${{ secrets.SAMPLE }}
